### ISSUE TITLE
Jar hell with the jasperreport plugin and JWT plugin with the jackson-xxx.jar

### ISSUE THREAD

**Issue by juanetec** [Servoy/servoy_jasperreports#2]
Hi,
I have update the jasperreport in the new servoy version (2021.06),
the new jasper have jackson-annotations-2.10.0.jar, jackson-core-2.10.0.jar and jackson-databind-2.10.0.jar and the plugin JWT have the same one but different version.
When I have put it in production the JWT plugin doesn't work, so I delete that plugin from the jasperreport folder an I have change the servoy_jasperreports.jar.jnlp to redirect thats .jar to the JWT folder.
Doing that both plugins works fine.

This is only a comment, I have solve it, is for the future, could you unify these versions to avoid this problem?

Un Saludo 

Juan Ramírez

**Comment by jcompagner** [comment]
i think the only thing you have to do is get the 3 jackson libs from the jwt plugin (those are newer with security fixes)
and replace the one from jasper.. (if you use smart client you need to replace them exactly, or adjust the jnlp file)

Or if you have both plugins and don't use smart client just delete the 3 jars of the jasper plugin.

there is already a case for this:

https://support.servoy.com/browse/SVY-16289

i guess we need to make a new release of jasper with those updated jackson libs (and maybe update jasper to .17)

**Comment by juanetec** [comment]
OK Thanks
